config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'ote_list' => 'static_pages#ote_list'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users
  
  get 'restaurant_name_search' => 'restaurants#search'
  get 'restaurant_signup' => 'restaurants#new'
  get 'restaurant_login' => 'restaurant_sessions#new'
  post 'restaurant_login' => 'restaurant_sessions#create'
  delete 'restaurant_logout' => 'restaurant_sessions#destroy'
  resources :restaurants
  resources :reviews, only: [:create, :destroy]
  i=1;
  while (i<9755)
   get "opinion_target_#{i}" => "static_pages#opinion_target_#{i}"
   i=i+1
  end

  j=1;
  while (j<11)
   get "/ot_list_OTE_YRRNorthYork_YRRCmodelBROWNW2V_1415combined_descending_#{j}.html" => "static_pages#ot_list_OTE_YRRNorthYork_YRRCmodelBROWNW2V_1415combined_descending_#{j}"
   j=j+1
  end

end

app/controllers/restaurant_sessions_controller.rb
class RestaurantSessionsController < ApplicationController
  def new
  end

  def create
  	    restaurant = Restaurant.find_by(name: params[:name], postal_code: params[:postal_code])
  	   
    if restaurant && restaurant.authenticate(params[:password])
      restaurant_log_in restaurant
      redirect_back_or restaurant
    else
      flash.now[:danger] = 'Invalid name/postal code/password combination'
      render 'new'
    end
  end

  def destroy
  	restaurant_log_out
  	redirect_to root_url
  end


end

app/helpers/restaurant_sessions_helper.rb
module RestaurantSessionsHelper

 def restaurant_log_in(restaurant)
    cookies.permanent[:remember_token] = restaurant.id
    self.current_restaurant = restaurant    
  end

  def restaurant_logged_in?
    !current_restaurant.nil?
  end

  def current_restaurant=(restaurant)
    @current_restaurant = restaurant    
  end

  def current_restaurant
    @current_restaurant ||= Restaurant.find_by(id: cookies[:remember_token])
  end

  def restaurant_log_out
  	self.current_restaurant = nil
  	cookies.delete(:remember_token)
  end

  def current_restaurant?(restaurant)
     restaurant == current_restaurant  	
  end


  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.url if request.get?
  end 
end

app/views/restaurant_sessions/new.html.erb
<% provide(:title, "Restaurant log in") %>
<h1>Restaurant log in</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_tag(restaurant_login_path, method: :post) do %>

      <%= label_tag :name, "Name: " %>
      <%= text_field_tag :name, nil, class: 'form-control' %>

      <%= label_tag :postal_code, "Postal code: " %>
      <%= text_field_tag :postal_code, nil, class: 'form-control' %>

      <%= label_tag :password, "Password: " %>
      <%= password_field_tag :password, nil, class: 'form-control' %>

      <%= submit_tag "Log in", class: "btn btn-success" %>
    <% end %>

    <p class="text-success">New restaurant? <%= link_to "Sign up as a restaurant.", restaurant_signup_path %></p>
  </div>
</div>